### ISSUE TITLE
AWS Resource isolation

### ISSUE THREAD

**Issue by nkrumm** [FredHutch/batchman#25]
In GitLab by @nkrumm on Oct 24, 2019, 22:18

We want to be able to isolate ECS/Batch/S3 resources between users/groups who use batchman.

Requirements/Specs:
- [x] Groups are defined in config.py, using ELMIRA groups. 
- [x] Groups have associated resources, defined in config. (Resources include: S3 buckets, AWS Batch queues + compute environments, IAM roles)
- [x] Groups have unique API keys. These are passed to `nextflow-runner` when launching a job.
- [x] ~~correct secret AWS credentials are specified when launching (while we wait on upstream nf patch to read ECS credentials on fargate...)~~ Patched Nextflow (PR pending upstream) to read ECS credentials.
- [x] create second set of resources on AWS (NGS/molmicro)
  + [ ] Does the EC2 instance role also need to be divided between workgroups?
  + [x] CE and queue
  + [x] independent IAM roles (with limited S3 credentials → see https://gitlab.labmed.uw.edu/uwlabmed/aws-admin/issues/67)
  + ~~[ ] independent subnets?~~
- [x] The `/api/external` routes are converted to internal only routes.
- [x] all other API routes need to validate user's group membership with the requested action.
- [x] The UI needs reflect:
  + [x] different groups on main workflow list page
  + [x] ability to select which group is launching a task in the launcher page
  + [x] list and detail views need to show group as appropriate

Additional features:
- [ ] we would like to be able to tag/bill by group → see issue #37
- [ ] ability to revoke API keys would be good
- [ ] can we provide introspection into IAM roles? → see issue #36 

Issues:
 - Nextflow does not currently read ECS IAM roles correctly (https://github.com/nextflow-io/nextflow/issues/1264) -- once this is resolved, we can remove the current 'hack' of providing AWS keys in the fargate container environment via the SSM (And can remove that access from the fargate task execution role). I am currently building the `nextflow-runner` docker image using a patched version of nextflow: https://github.com/nkrumm/nextflow/commit/a998c49b04236add62b0a4d06d9fba087d0bacda
 - [x] DONE. the ECS event reporting currently uses a API key baked into the cloudformation setup. We will either need to use a generic API key for these events, or perhaps just use an internal endpoint without keys? If latter, the lambda function that currently ingests the Batch CloudWatch events needs to be brought into the VPC so that the internal endpoint is visible to it.
